name: organicplants
description: "A modern Flutter-based e-commerce app for organic plants, featuring Firebase integration, user authentication, product browsing, cart, wishlist, and smooth UI animations."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  http: ^1.3.0
  provider: ^6.1.4
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: 5.1.1 
  shared_preferences: ^2.2.0
  animated_text_kit: ^4.2.3
  flutter_screenutil : ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  cloud_firestore: ^5.6.12
  firebase_core: ^3.13.0
  firebase_auth: ^5.7.0
  cloud_functions: ^5.6.2
  google_sign_in: ^7.1.1
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^15.2.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



