name: organicplants
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  http: ^1.3.0
  provider: ^6.1.4
  pinput: ^5.0.1
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  firebase_auth: ^5.5.3
  smooth_page_indicator: ^1.2.1
  carousel_slider: 5.1.1
  adb_wifi: ^1.0.2
  shared_preferences: ^2.2.0
  animated_text_kit: ^4.2.3
  flutter_screenutil : ^5.9.3
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ltree.png
    - assets/app_logo.png
    - assets/No_Plant_Found.png
    - assets/No_WishList.png
    - assets/stree.png
    - assets/splash screen/
    - assets/onBoarding/
    - assets/banner/
    - assets/category/
    - assets/features/
    - assets/payment_success/

